### ISSUE TITLE
Match relocation data tracking issue

### ISSUE THREAD

**Issue by em-eight** [riidefi/mkw#227]
Currently, only binary sections are matched and the relocations are simply copied from the original file. This can result in seemingly matching binaries that in actuality are linked incorrectly. Relevant issues: #211 #101 

- [x] Generate relocatable ASM
- [x] Update .cpp inline ASM functions with relocatable ASM
- [x] Convert desired ELF relocations to nintendo relocations
- [ ] Add `verify_relocations.py` that verifies generated relocations and outputs results to stdout.

Relevant project: https://github.com/SeekyCt/ppcdis
